spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unma
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
      generate-ddl: true
    show-sql: true
